import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
import Footer from "../components/Footer";
import I18nProvider from "../components/I18nProvider";
import { ThemeProvider } from "../context/ThemeContext";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider>
          <I18nProvider>
            <Header />
            {children}
            <Footer />
            <Link
              href="https://wa.me/51901211995?text=Hola%20Ciclo%20-%20MP%20Recicla%20S.A.C."
              target="_blank"
              rel="noopener noreferrer"
              style={{
                position: "fixed",
                bottom: "24px",
                right: "24px",
                zIndex: 1000,
                background: "#25D366",
                borderRadius: "50%",
                width: "56px",
                height: "56px",
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                boxShadow: "0 2px 8px rgba(0,0,0,0.2)",
              }}
            >
              <img
                src="/img/whatsapp.svg"
                alt="WhatsApp"
                style={{ width: "32px", height: "32px" }}
              />
            </Link>
          </I18nProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
